ansible_become_pass: ENC[AES256_GCM,data:OaNEus8nqkI=,iv:LV3c4MCok4dp6eECgPxo3nBwH5vYgRqp53LhgNKjOu0=,tag:3tq+nGM0AK01qvfrvh2FWA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1j3w36df2s8y5am645ymk93xxfrnse5y4qyd4yt595xrhuaxhn3zqwctsya
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmN3NQUVZPblBvdTM5UnRm
            c05reDFtYVQ5N3orcW1hRWtIazhtWllwSHlVCis1R2RCdW8reUpNNU42c2lheG9E
            NlFTT2FqM25jbDY0bGJ3eWpvcDRIclkKLS0tIHgwbFZFeWV3VFAvSWxLMmIyQjdr
            RlcreGxkUWxMQmVZalhQUzhoOWhZNUEKH5L0+MjQoHRuzpz3o+MOo2VHlh3qms2/
            KfZ77H681dydAS1ZX6aFVq+yMjyDzlurjwG+Yhr+4aaSMzMu+xczWw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-12-19T15:27:24Z"
    mac: ENC[AES256_GCM,data:ThEAZhkkL7bh0v6aGMMhCJWoOviUtzrhVcKEnvjLvDxAOzZi0DHgW2rr5S9YFU/8lJWOnXnm/IdejFAoHx9e4IeBsTNq5NW/uhqLrEILs5Hde+Nx6vBmXU9WjhOXVWBkip9maDGlliCepoLtVNqYS2sabwae3yxJSbBWb4I0wlo=,iv:/ZCGEudT74UmbuFaAUXn1Wr8EWSkZDrhqet2qtsxAYY=,tag:bL5E6/Bqi5MvfC7rDOSThw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
