---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: transition
provisioner: nfs.csi.k8s.io
parameters:
  server: behemoth
  share: /export/tnw
reclaimPolicy: Delete
volumeBindingMode: Immediate
mountOptions: ["hard", "noatime"]
