apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
stringData:
    api-token: ENC[AES256_GCM,data:GpTbajS7EryM8SNzsHkx0fWLvRkBXSjIvcOLdRLObzuhbAEyWU3XNg==,iv:BgSN/Vy19sSytbojl1hgM1ivVazRbZMR7tu2I41bDG0=,tag:c0Tw5i8fRYT1hEEgDLNvzg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1j3w36df2s8y5am645ymk93xxfrnse5y4qyd4yt595xrhuaxhn3zqwctsya
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmdjcyaXpLUjNqZzl5d1U0
            MEdGRUxodHIvVjdDKzFwQllOZ0ZqK2ptZFQ4CllGOHZHdk41MFBURm1KUW5zNzJY
            T1JMdUprOVh0YzNiRTBmWktpQU04OFEKLS0tIEIxNjVmaG9pcktwRVkyWXAyaVpJ
            NS9nWkE1QThndG1Ua2Z1eWJkM3EyNzgKvV8qCLeEPT+bGBiNzPneYoxwHt/9wWdb
            O5SO9LQfr6zsjG/32zK9oHepcDbEVW6UGCRWfOBaKxIZrZonaQCXhg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-12-19T14:22:59Z"
    mac: ENC[AES256_GCM,data:Fm5oTGnYHQirohybYRpef5ivQZKQ1KcLfSXOcjG/At0OQ1efSWY96F1Ym4VV9FfGqe5rPUF8snVRds4mGOOYyF8b0x4v0wRsY/Yz7vbYD+53EsgVr1lQIxy3/5Di1ooPz2CFVeTjBjrxyD6hy6+M/62UTDCkJdgp9pmfxd5hz80=,iv:ZPHt9tXyYkqw7JCPvu4LhP1kWrlLXNvRMe25iXX5YuM=,tag:eKfGij/joGz9u1UR3PZEgQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
