apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:WiJNAbWTorLc/uSlvn9Ts1f0FP90nNEdX0Hr2j/QG09irJyt,iv:WNf5ve1dR6320SfUXOGcAcYZUfPD8xPdiwRfHkkmdlY=,tag:zD5NJb+P0H3Wy2/+u1tr+g==,type:str]
    credentials.json: ENC[AES256_GCM,data:NKjUQ72ahe5x2SNJ2VuKh+9OEztkD83g6xmi4zYQjxjxcIV5joJ1dHiYZmDg/wP0GOCyN14AbVE0FEmH387PYeMX/67HgqarfRuR9hs5/6EK152MZ+0idY7/qgbMpbBiprlRYMuUkxjYLSgwN9lMR1RbCbJlS1pmIiydSjofIw5j2k0OnuLKw87Z+snk+Ilq34DXzw/6HFDuXN95HKv4XwOkScGcO/thLeKv8vXEWQ==,iv:zqJr+PHa0luFdPvYId7jkay0YdZRzTgoUIVClcsmFeg=,tag:O3CBMEkK4X+OUV5a+RgQHg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1j3w36df2s8y5am645ymk93xxfrnse5y4qyd4yt595xrhuaxhn3zqwctsya
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIaG93MFJrL1RYcnBoTXdR
            QU1wdkpLY0YxZ1RBejNlcHNOdlNUaE9mdGwwCllEYVRqSWQ3R3VUSUNoYmNFOG16
            SDdQTm5sQ3d2WXBzcEVQL2JmSEVYSjgKLS0tIGRlTTZsY3RSSUhraEVqaDhXdjJ0
            WlU0cVF5a1U4NlNMV0JkbnRiZ010bjgKQJR6iU/NJPV0vwkST6dKDY2o4yGmVwis
            KZJ0mexcYTpNqp37E1t6ubqpiZXeW1fGWJaa0jkZykoslz1cEpEpxA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-12-18T14:30:07Z"
    mac: ENC[AES256_GCM,data:3yzDTjevx8DbjcpiISICVBqR9nZgrEYiQqvoc5PQ0X6RNq5SJOYLvgFeah6r9zY5/4ywlD2I5nUHcih7ssQwQlXFeGXlPkT5yxt8SMkkNbvQOjR6lIteq2N6byP7PgBx21gdnhgrsT7HPBU/jOh/L4MBY6Eif0DrGlz4wmgmm4w=,iv:8REYb82sVelh3tg51WiiQ9AVK8ycJJwe8SFiGlj9whw=,tag:+7nYxXFPFcGCjHS6vodfMw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
