apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:2U8DRUINsNkEYj0vLldxXC9FsGdguk8SK3zmL/Po88K8QuAF,iv:DHUl4F4y16ZP9t8893uZQWJ2YnROMeYnTd1YgnRCM9o=,tag:PHorVo7gD6w6ONolyMmHlA==,type:str]
    credentials.json: ENC[AES256_GCM,data:hZQqLUE7dSdSxPjgxrOwA2WNUt8FtN9CYio34vAhtHlgHp1BehBelDXr1WUmy4k5WHBzDsXbEqkW0EaThyBT2ov0S55+u9f1ngDa+51uPq9C0xXBbVNW7LGxpfeMs6JO5eHNUysJg2EwjNsolNxUvfbkV0WBfnhBYRPbu8bm8JBKDeg7ZxdVJ12wwbVtPFIhAbfMbIByj7quQ21Yn4DvT54zjd7N+j520WrD/DlokQ==,iv:NoT7S01PaYfO2fjsNUQz9jjj6B6C2GmfFhMIeiaaN4o=,tag:dvJAaHuyZ2AR/vTH+4B6fw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1j3w36df2s8y5am645ymk93xxfrnse5y4qyd4yt595xrhuaxhn3zqwctsya
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBV3ExYjMva2kzSTd4MHJQ
            REJXRVFhUHpkQkVNZnpRQUNNRCs0SWZLdFV3CjB5RXRua2lpbEFWblhSaVFwS21o
            NFlzV2ozakJtbkhOM29tVjdTY0FSZncKLS0tIEdGS1pDL1EvSmVnV0UxRTVwQ1Ey
            N0pMUFRtWUxJa1FSNDVYOEZQTzViaFUKXbojb5PKnW34+7ffGmyrE6xbMkxg4CT3
            wLIrwxqmAMTeJIMMkIn5DOtD8PSL+RpBKYGlp3ZVhlh3XbYXEpwD5g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-12-19T15:28:25Z"
    mac: ENC[AES256_GCM,data:xYaUTIs4CEN8lbrCgktDm9ItxvQ6URbwHnaj5mnHs5Q0Lo+KnJ+OeBCtgZ8GRdpiY4kJ0nBq1rdY+yDkTMhuiHANgYq5tKFmW5R2mc4d7Mm/ZiqsIQ5d1IYmoyt+X/ODq7WHOO09LSSIuzvDNC15ZL15rj1vfSZ1085S47b/RM0=,iv:PN8oqg/gqkoRNoqhX9JbMBs5TMQ67qbwQISWP2FzfIg=,tag:F9JAI+Lw4mxycPtlYALJxQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
